### ISSUE TITLE
PublicActionStatus is only exported as a type, not as a value

### ISSUE THREAD

**Issue by westmark** [contentful/ui-extensions-sdk#290]
`PublicActionStatus` is defined as an `enum` in `typings.d.ts`, but has no equivalent in the exported JS. So importing it and using it, e.g. `PublicActionStatus.Succeeded`, results in a runtime error.

**Comment by davidfateh** [comment]
Hi @westmark this should now be fixed in 13.14.2. Please let me know if that works for you.

**Comment by westmark** [comment]
Hi @davidfateh. `PublicActionStatus` is still not exported as a value. Using it yields an error. I think the underlying cause is in Parcel somewhere. See https://github.com/parcel-bundler/parcel/issues/3624  Running `tsc` with `noEmit` reset to false yields this

```var PublicActionStatus;
(function (PublicActionStatus) {
    PublicActionStatus["Scheduled"] = "scheduled";
    PublicActionStatus["Succeeded"] = "succeeded";
    PublicActionStatus["Failed"] = "failed";
    PublicActionStatus["Canceled"] = "canceled";
})(PublicActionStatus = exports.PublicActionStatus || (exports.PublicActionStatus = {}));```

But a search for PublicActionStatus in the parcel output returns zero results.

**Comment by davidfateh** [comment]
I see. Unfortunately, if it means that our bundling of the package is causing this issue, then it might be a bigger dig.

However, since you're using typescript you should still get an error when trying to use a status which doesn't exist as long as the code is typed accordingly. For example:

```js
const status = scheduledAction.status as PublicActionStatus;

if (status === 'foo') { ... } // this will throw a ts error since `foo` is not part of the `PublicActionStatus` enum and the condition will never be true.
```

Is there a specific use-case you were hoping to achieve which wouldn't be covered by my example above?
